name: 'Bug Report'
description: 'Report a bug found in the latest update.'
labels: 'bug report'
body:
- type: markdown
  attributes:
    value: "# Thank you for submitting!"
- type: input
  attributes: 
    label: 'Bug Description'
    description: 'Clear and concise description of the bug.'
    placeholder: 'You know this one is required, right?'
  validations:
    required: true
- type: textarea
  attributes:
    label: 'Reproduce'
    description: 'Steps to reproduce the bug.'
    placeholder: 'Please be specific.'
  validations:
    required: true
- type: input
  attributes:
    label: 'Version Number'
    description: 'Build this bug was found in.'
    placeholder: 'Semantic Versioning cool'
  validations:
    required: true
